---
- name: Install Gatekeeper
  #command: kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-{{ ilke_features.gatekeeper.release }}/deploy/gatekeeper.yaml
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-{{ ilke_features.gatekeeper.release }}/deploy/gatekeeper.yaml
